- .github/workflows/main.yml
Keeping consistent with other pipelines
> ci: rename GHA job to CI_Pipeline

- module-assets/.pre-commit-config.yaml
Added some exclusions for the pre-commit yaml check in order to temporarily allow full pre-commit to work with existing files.
> fix: added exclusions for pre-commit yaml check

- commonRenovateConfig.json
The renovate pipeline is spitting errors like this:
```
"response": {
"statusCode": 405,
"statusMessage": "Method Not Allowed",
"body": {
"message": "At least 1 approving review is required by reviewers with write access.",
"documentation_url": "https://docs.github.com/articles/about-protected-branches"
},
```
Solution: disable auto merge in the common renovate config file. We have our own auto approve / merge script that we can roll out when we are comfortable with auto merging renovate PRs on the `terraform-ibm-modules` org
> ci(renovate): set automerge to false

- .github/workflows/release.yml
Changed the shared release pipeline to use the CI Container.
Could not use Makefile sem-release step due to some folder mismatch between that step and the way Github Actions sets the container up.
Am calling `npx semantic-release` directly in workflow step, but inside container which has all `npm` plugins pre-installed.
> chore: shared release workflow using container

- module-assets/ci/run-tests.sh
No need to run tests if a PR only contains a change to `".github/workflows/ci.yml"` or `".github/workflows/release.yml"`
> ci: run-tests.sh - update skip array

- commonRenovateConfig.json
PR to set [branchConcurrentLimit](https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit) to 0 (no limit).
Why? See https://github.com/renovatebot/renovate/discussions/16426
> ci: set branchConcurrentLimit to 0 (no limit)

- module-assets/ci/run-tests.sh
We don't need to run tests if a PR only contains updates to `.one-pipeline.yaml` just like we already have for `.travis.yml`
> ci: add .one-pipeline.yaml to the skip tests array

- module-assets/.pre-commit-config.yaml
- module-assets/basic-pre-commit/.pre-commit-config.yaml
Reverts terraform-ibm-modules/common-dev-assets#68
Looks like a regression so need to revert:
```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1
```
This always fails, but no docs are updated by the hook
REGRESSION -> https://github.com/antonbabenko/pre-commit-terraform/issues/413
> Revert "chore(deps): update pre-commit hook antonbabenko/pre-commit-terraform to v1.74.0"

- module-assets/.pre-commit-config.yaml
at the end `terraformDocs` script deletes examples.md. It looks like hook touches README.md multiple times, and after first touch examples.md file is deleted. Therefore we get an error: 
```
Add examples section to README...........................................Failed
* hook id: add_examples
* files were modified by this hook
Error: template: content:3:3: executing "content" at <include "EXAMPLES.md">: error calling include: open EXAMPLES.md: no such file or directory
Error: template: content:3:3: executing "content" at <include "EXAMPLES.md">: error calling include: open EXAMPLES.md: no such file or directory
README.md updated successfully
helmlint.................................................................Passed
Makefile:85: recipe for target 'pre-commit' failed
make: *** …
```
> fix: Update Add examples pre commit hook

- module-assets/ci/terraformDocExamples.py
Example name, which is added to Examples section, is generated from a title of an each Readme example file. If hashtag is included we need to remove it
> fix: Remove hashtag from Examples section (README)

- module-assets/ci/terraformDocExamples.py
If the metadata tags (BEGIN EXAMPLES HOOK) don’t exist, the hook does not add anything.
> fix: Do not run examples pre-commit hook if metadata does not exist

- module-assets/.pre-commit-config.yaml
Reverts terraform-ibm-modules/common-dev-assets#104
It seems to clash with the add_examples hook - need to debug and will add it back after
> Revert "ci: add mixed-line-ending hook"

- module-assets/.pre-commit-config.yaml
After adding the terraform-config-inspect hook, checkov is failing for some modules on the content of module-metadata.json
EG: `iam-account-settings-module`:
```
Passed checks: 0, Failed checks: 2, Skipped checks: 0
Check: CKV_SECRET_6: "Base64 High Entropy String"
FAILED for resource: 50c5527d09191147222b2280e363ac8ef97bfa3a
File: /module-metadata.json:324-325
324 |         "restrict_create_platform_apikey": "api*********",
Check: CKV_SECRET_6: "Base64 High Entropy String"
FAILED for resource: b939bb67ee5f5b13f7997dba58c31813ce8033f0
File: /module-metadata.json:324-325
324 |         "restric************************": "api_creation",
```
Since this file is auto generated, I think it is OK to add to ignore list
- Make sure to …
> ci: configure checkov to ignore module-metadata.json

- module-assets/.pre-commit-config.yaml
Add mixed-line-ending pre-commit hook
default settings of mixed_line_ending pre-commit hook have issues with terraform_docs hook. Therefore we need to force to use LF ending
>  Whereas Windows follows the original convention of a carriage return plus a line feed ( CRLF ) for line endings, operating systems like Linux and Mac use only the line feed ( LF ) character
example doc: https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repo_pre_commit_hooks/mixed-line-ending/mixed-line-ending.html
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if …
> ci: add mixed-line-ending pre-commit hook

- module-assets/.pre-commit-config.yaml
ci: configure detect-secrets to ignore module-metadata.json as it is an automatically generated file
> ci: configure detect-secrets to ignore module-metadata.json

- module-assets/ci/run-tests.sh
Don't run tests if only the module-metadata.json file is being updated in PR
> ci: Don't run tests if only the module-metadata.json file is being updated in PR

- module-assets/ci/terraform-config-inspect.sh
We generate terraform metada only for terraform modules. To check if repo is terraform module we check for `.tf` files inside root only
> fix: Run Generate terraform module metadata only for root tf files

- module-assets/ci/run-catalog-onboarding-pipeline.sh
`git rev-parse --show-toplevel` does not work in travis the way we mount repo code as a volume. So updating to use `git config --get remote.origin.url` which does work.
Testing:
Currently you get:
```
root@cb931b6b7032:/mnt# basename $(git rev-parse --show-toplevel)
mnt
```
With the fix you get:
```
root@cb931b6b7032:/mnt# basename "$(git config --get remote.origin.url)"
terraform-ibm-landing-zone
```
> fix: update the command used to determine repo name in run-catalog-onboarding-pipeline.sh

- module-assets/ci/run-catalog-onboarding-pipeline.sh
- add validation around value of `--github_org`
- rename `--destroy-on-failure` -> `--destroy_on_failure` for consistency with all other args (flag not being used anywhere yet, so OK to add this breaking change)
- remove `--programmatic_name_prefix` flag - the pipeline is being updated to automatically determine this
> ci: add extra validation to run-catalog-onboarding-pipeline.sh

- module-assets/Makefile
Changed the Makefile task "run-go-module-tests" to exclude any test packages from the "common-dev-assets" directory, as those tests are not intended to be run during a Golang module project's unit tests.
> fix: makefile skip common dirs for go-module tests

- module-assets/ci/install-deps.sh
Revert back to Terraform v1.2.9 (https://github.ibm.com/GoldenEye/issues/issues/2858) and disable renovate from bumping it
> Revert back to Terraform v1.2.9

- module-assets/ci/terraformDocExamples.py
Run examples hook only inside folder which has README file and tf files
> fix: run examples hook only when tf files exist

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Adds info to the template readme file about setting the rep name and description in the settings.yml file
Related PRs:
- https://github.com/terraform-ibm-modules/documentation/pull/23
- https://github.com/terraform-ibm-modules/terraform-ibm-module-template/pull/142
> add settings info to readme

- module-assets/ci/install-deps.sh
We need to go to >=1.3.0 in order to migrate some modules away from the Experiment "module_variable_optional_attrs"
See https://developer.hashicorp.com/terraform/language/upgrade-guides
> ci: update to terraform 1.3.3

- module-assets/.pre-commit-config.yaml
Replace checkov pre-commit hook with official one so checkov no longer needs to be installed locally (this hook install it as part of a virtual env)
> Replace checkov pre-commit hook with official one

- module-assets/Brewfile
- module-assets/Makefile
- repo_migration.sh
We no longer require Brew since checkov does not need to be installed anymore after merging https://github.com/terraform-ibm-modules/common-dev-assets/pull/222
> ci: remove brew dependency

- .github/workflows/ci.yml
- .secrets.baseline
- pipeline-assets/contanerize.sh
With Brew gone, we no longer need to source the .bashrc or .profile
> ci: remove source of .bashrc and .profile

- module-assets/ci/install-deps.sh
ci: add support to install-deps.sh to place binaries into custom location. 
It will be used by the new IaC Tekton pipeline to ensure we lock into exact dependency versions across all pipeline stages.
> ci: add support to install-deps.sh to place binaries into custom location

- module-assets/.pre-commit-config.yaml
https://github.com/pre-commit/mirrors-isort is now deprecated and we should be using https://github.com/PyCQA/isort instead
> ci: update isort pre-commit hook

- module-assets/ci/terraformConfigInspect.py
terraform-config-inspect hook uses IBM provider from terraform cache (.terraform folder). It can happens that cache contains older versions. To make sure we always use the latest version of provider only, we need to delete old versions before we run `terraform init`.
> fix: remove IBM provider from terraform cache

- module-assets/ci/run-tests.sh
If a PR only contains a change to `cra-tf-validate-ignore-goals.json` it shouldn't need to run the tests as it doesn't change any module code. 
> add cra-tf-validate-ignore-goals.json to skip_array

- module-assets/.pre-commit-config.yaml
- renovate.json
lock into checkov version and disable with renovate until custom rule is added
> fix: lock into checkov version and disable with renovate

- module-assets/.pre-commit-config.yaml
- renovate.json
renovate will attempt to bump the checkov pre-commit version to the latest github tag, however checkov do not create github releases for every tag, and therefor a permanent branch is not created for every tag, and so pre-commits won't work on the git tag. This fix will only allow renovate to bump based on new git release versions, and not the tags.
> fix: custom rule for checkov

- commonRenovateConfig.json
We need to bump to minimum required version for all modules to 1.48.0 to pickup the fix / workaround for https://github.ibm.com/GoldenEye/issues/issues/3072
Once done, we will revert back
> ci: temporarily enable and priortise bump of ibm provider

- commonRenovateConfig.json
ci: disable bumping of required_provider versions by default
> ci: disable bumping of required_provider versions by default

- repo_migration.sh
remove Brewfile refs from migration script - we don't use brew anymore
> fix: remove Brewfile refs from migration script

- module-assets/ci/cra-tf-validate-ignore-goals.json
CRA scans are failing on goal `3000802` - we need to ignore this goal to unblock pipelines. 
I have created a CRA issue to track why the goal is failing
> ci: update cra-tf-validate-ignore-goals.json

- common-go-assets/icd-region-prefs.yaml
Reverts terraform-ibm-modules/common-dev-assets#275
us-east is a valid region for instance deployment. The confusion is that the doc says:
> Only keys in the `us-south` and `eu-de` are durable to region failures. To ensure that your backups are available even if a region failure occurs, you must use a key from `us-south` or `eu-de`, regardless of your deployment’s location
They key here being "regardless of your deployment’s location"
> Revert "Update icd-region-prefs.yaml"

- module-assets/.pre-commit-config.yaml
- renovate.json
After some testing it seems all git tags do work with the pre-commit hook, so re-enabling the renovate rule
> re-enable bumping checkov with renovate 

- module-assets/ci/run-tests.sh
We need to now use `set -o pipefail` to ensure we correctly capture the exit code of the tests, otherwise due to the fact we use `tee`, the tests will always exit with a 0 result, which is not correct
> set set -o pipefail in run-tests.sh

- module-assets/ci/submoduleVersionCheck.sh
Before we check submodule version with primary branch we need to have the latest version of primary branch first. Therefore we clone a new copy of it before we do comparison. 
> fix: git-submodule-version-check hook check version with local primary branch

- module-assets/ci/submoduleVersionCheck.sh
We need to make sure that the PR submodule commit id is the same or older than primary branch  submodule commit id.
> fix: check all commit ids of a submodule

- commonRenovateConfig.json
The latest ibm provider contains a couple of fixes we want to consume across the board. The main one being https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4209 which was causing rate limiting issues
> ci: enable provider bumping in order to consume latest ibm provider

- module-assets/Makefile
need to mount netrc file for the git submodule version check hook to work in travis
> ci: mount netrc in pre-commit make commands

- module-assets/Makefile
In https://github.com/terraform-ibm-modules/common-dev-assets/pull/345 we added support to mount the netrc file into the make commands that run pre-commits, since one of the pre-commits now needs it to do a git clone.
The command we used seems to be failing with:
`cp: cannot stat '/home/travis/{.netrc,.ssh}': No such file or directory`
So splitting the command into separate lines
> ci: fix the copy command for netrc

- commonRenovateConfig.json
All repos have provider versions updated to >= 1.49.0, so disabling the rule.
> ci: disable required provider updates

- module-assets/Makefile
we need to change group ownership for ssh and netrc files inside pre-commit-no-terraform make cmd
> fix: add change group ownership for ssh make pre-commit

- pipeline-assets/contanerize.sh
Currently if the docker build command fails, it will proceed to try validate, push to ICR and VA scan against an image that does not exist. This means it can be hard to actually identify the root cause to a failing pipeline, as there will be a lot of log noise like this:
```
-- VALIDATING LOCALLY BUILT DOCKER IMAGE --
docker run --tty ubi8-squid-proxy whoami
Unable to find image 'ubi8-squid-proxy:latest' locally
docker: Error response from daemon: pull access denied for ubi8-squid-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make: *** [Makefile:69: docker-validate] Error 125
API endpoint:      https://cloud.ibm.com/
Region:            us-east
User: …
```
> ci: update logic in contanerize.sh

- module-assets/ci/install-deps.sh
terraform-docs.io seems to be down, so updating to pull from github instead
---
> ci: pull tf docs from github

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Add a link to the public docs about the reference architecture. Adding this because the template is no longer in the module template.
GitHub issue: https://github.com/terraform-ibm-modules/terraform-ibm-issue-tracker/issues/54
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or …
> docs: add info about ref arch

- .github/settings.yml
I noticed that our main branch protection rule in this repo was not requiring the `CI_Pipeline` status check to complete before being able to merge. The config in settings.yml was incorrect. The code in this PR should fix it
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or …
> ci: fix the repo setting config

- module-assets/ci/run-tests.sh
Added the "parallel" flag to `go test` call in order to control the maximum allowed parallel test threads regardless of CI platform.
Use the `-parallel=n` flag for Go tests, in order to control the maximum allowed parallel test threads. The default value when flag is not supplied was too varied amongst all CI platforms, this will allow more parallel tests to be run in environments with limited CPU.
---
> fix: add parallel flag to go test

- commonRenovateConfig.json
By having `prConcurrentLimit` set to `1` we are finding that things like the common-dev-assets git submodule and the test wrapper version can remain on very old versions because renovate is set up to priortise creating updates for terraform dependencies first. By setting it to `3` it should at least allow terraform dependencies, git submodule and go dependencies to be updated
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by …
> ci: allow up to 3 renovate PRs to exist at any given time

- commonRenovateConfig.json
- For modules that currently have `required_version = ">= 1.0.0"` this rule will not do anything.
- For modules that have `required_version = ">= 1.2, <= 1.3"` this rule will widen the range like so:
---
> ci: enable rule to bump terraform required_version

- module-assets/.pre-commit-config.yaml
Exclude "end-of-file-fixer" for svg files
---
> fix: exclude end-of-file-fixer for svg files

- common-go-assets/cloudinfo-region-power-prefs.yaml
as the test are creating deployments in same region because of priority. ssh key causes a problem
for example, syd04 and syd05 powervs zones are mapped to au-syd region on VPC side. Test is picking up the first 2 regions.
this creates 2 slzs in au-syd. This causes a problem, beacause of duplicate ssh key created by default and upgrade example
---
The commit message …
> fix: change order as ssh key is conflicting

- .secrets.baseline
- module-assets/.pre-commit-config.yaml
This will address the error we are currently getting:
```
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1
Traceback (most recent call last):
File "/home/travis/.cache/pre-commit/repo1hege4pi/py_env-python3.9/lib/python3.9/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/travis/.cache/pre-commit/repo1hege4pi/py_env-python3.9/lib/python3.9/site-packages/urllib3/contrib/__init__.py)
```
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the …
> ci: bump detect secrets to 0.13.1+ibm.60.dss

- commonRenovateConfig.json
We haven't run renovate in a long time, so I'm setting `prConcurrentLimit` to `1` so when I do run it, only 1 PR will be allowed in each repo at any given time, meaning we won't trigger a load of parallel tests. Once we roll out triggering pipeline with comments, we can set this to any number, but only leave a comment in 1 PR
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the …
> [renovate] Set prConcurrentLimit to 1

- commonRenovateConfig.json
In order to run pre-commit hooks, we need to install dependencies into the dependency updater image
> Further updates to commonRenovateConfig.json for "postUpgradeTasks"

- common-go-assets/cloudinfo-region-secmgr-prefs.yaml
- common-go-assets/cloudinfo-region-vpc-gen2-prefs.yaml
At the request of management in IBM, remove all Japan regions (tok, osa) from IBM Cloud test run preferences.
We will be notified by management when we should add them back into test rotation.
```
/run pipeline
```
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any …
> test: remove japan regions from test prefs

- module-assets/ci/install-deps.sh
Last version that is not BSL.
Legally the modules could be run with a higher version (modules are outside the scope of BSL), but we're simply putting this as a way we ensure that the modules do not contains logic from >1.5.5 version which would make it impossible to run in Schematics.
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new …
> ci: lock into TF v1.5.5

- common-go-assets/cloudinfo-region-secmgr-prefs.yaml
- common-go-assets/cloudinfo-region-vpc-gen2-prefs.yaml
Enable Japan regions for testing in the `common-go-assets` test region configurations.
```
/run pipeline
```
> fix: enable japan regions for testing

- module-assets/ci/terraformDocGoMod.py
> fix: add warning message if go mod pre-commit hook fails

- module-assets/.pre-commit-config.yaml
- module-assets/ci/install-deps.sh
- remove terraform-config-inspect hook
- no longer install the tool as a dependency
```
/run pipeline
```
> remove terraform-config-inspect hook

- module-assets/ci/run-tests.sh
- module-assets/ci/trigger-catalog-onboarding-pipeline.sh
- add extra curl flags to webhook trigger in trigger-catalog-onboarding-pipeline.sh - without the flags, the command can fail silently 
- add `.catalog-onboard-pipeline.yaml` to the ignore array so tests will not run if a PR runs to only update this file
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message …
> add extra curl flags to webhook trigger in trigger-catalog-onboarding-pipeline.sh

- pipeline-assets/image_vuln_scan.sh
migrate to v4 VA image report api
```
/run pipeline
```
> fix: migrate to v4 VA image report api

- common-go-assets/cloudinfo-region-secmgr-prefs.yaml
We do not have an increased quota for trial secrets manager instances in the eu-es region. This causes test failures in any test that wants to create a SM instance.
```
/run pipeline
```
> ci: remove madrid from SM tests

- module-assets/ci/run-tests.sh
Need to temporarily enable trace logging in run-tests.sh to debug an issue
```
/run pipeline
```
> temporarily enable trace logging in run-tests.sh

- module-assets/ci/run-tests.sh
Additional logic added to prevent tests from running on an empty commit.
```
/run pipeline
```
> fix: run-tests.sh doesn't test on empty commit

- module-assets/.pre-commit-config.yaml
- renovate.json
Locking into 3.1.55 due to this bug -> https://github.com/bridgecrewio/checkov/issues/5945
```
/run pipeline
```
> lock into checkov 3.1.55

- module-assets/ci/install-deps.sh
Adding support for macOS intel architecture in trivy dependency download in install-deps.sh
support for macOS intel architecture in trivy dependency download in install-deps.sh
```
/run pipeline
```
> Update install-deps.sh to support intel arch on macOS

- module-assets/ci/install-deps.sh
We are going to temporarily lock our CI environment into using terraform 1.5.7 while we update the version constraints of all our modules to allow terraform 1.6. It means we won't hit any circular dependency issues since CI runtime will still use 1.5.7. 
Once we have updated all modules, we will switch our tests to start using opentofu.
I'm also removing terragrunt, as we no longer need it, and also adding opentofu.
Removed tfswitch too, and updated the downloads to use `amd` or `arm` depending on what it detects in the runtime OS.
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following …
> ci: lock into terraform 1.5.7

- module-assets/.pre-commit-config.yaml
Update trivy hook to ignore common-dev-assets git submodule
```
/run pipeline
```
> Update trivy hook to ignore common-dev-assets git submodule

- module-assets/ci/install-deps.sh
OpenTofu 1.7.0 is now officially released, but we do not want to use it yet because our Terraform modules are still set to only allow 1.6.x.
Removing the renovate tag to fix tofu version to the last v1.6.2 version.
```
/run pipeline
```
- …
> fix: set static tofu version in install-deps.sh

- module-assets/Makefile
- module-assets/ci/run-tests.sh
increase golang test timeout to 10 hours for MAS DA tests
```
/run pipeline
```
> increase golang test timeout

- module-assets/ci/run-tests.sh
The array to check the skip files has been moved to an else block after checking the length of it. This should fix the problem as we may be running into the same problem as the comment states that $file_array[@] will return 1 even if it is empty so it would be running the loop at least once, switching match to false.
```
/run pipeline
```
- Include information that users need to …
> fix: updated to not run tests on empty commit

- module-assets/ci/run-tests.sh
This PR addresses the change to modify the array only if the repo name starts with `stack-`
Refer [Issue-9655](https://github.ibm.com/GoldenEye/issues/issues/9655)
```
/run pipeline
```
> feat: updated skip array based on repo name

- module-assets/.pre-commit-config.yaml
- module-assets/ci/run-tests.sh
This PR fixes a bug identified in the [PR-1007](https://github.com/terraform-ibm-modules/common-dev-assets/pull/1007) 
```
/run pipeline
```
> fix: corrected the pattern required to match stack repos.

- common-go-assets/cloudinfo-region-secmgr-prefs.yaml
Remove us-south and us-east from secrets manager test region selector per announcement from Secrets Manager team.
Announcement: https://ibm-cloudplatform.slack.com/archives/C010Z1DQ05N/p1724936766805639
```
/run pipeline
```
- Use the …
> ci: remove us regions from SM tests

- module-assets/.pre-commit-config.yaml
We do not want checkov to verify `github_configuration` checks. Checks such as the below are being seen in some pipelines:
```
Check: CKV_GITHUB_26: "Ensure minimum admins are set for the organization"
FAILED for resource: /github_conf/org_admins.json.*./github_conf/org_admins.json.CKV_GITHUB_26
File: /org_admins.json:1-221
```
```
/run pipeline
```
- Include information that …
> skip checkov github_configuration checks

- common-go-assets/common-permanent-resources.yaml
Expose the persistent MQ capacity service instance CRN for consumption by the DA.
CRNs contain more information and are a more comfortable resource to work with in DAs.
Expose the persistent MQ capacity service instance CRN
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release …
> feat: expose persistent MQ capacity instance CRN

- common-go-assets/common-permanent-resources.yaml
Added test sdnlb resources
```
/run pipeline
```
> feat: add test sdnlb resources

- common-go-assets/common-permanent-resources.yaml
Updated test sdnlb secret id, and secret group
Added allow-listed service id for sdnlb
```
/run pipeline
```
> update permanent test sdnlb secret

- module-assets/ci/run-tests.sh
We want to purposely run tests in PRs with 'common-dev-assets' GIT submodule updates since terraform version can change, and we will want to run full set of tests if that happens.
```
/run pipeline
```
- Use the **Squash and merge** …
> PR should run infrastructure tests when common-dev-assets is being updated

- module-assets/ci/run-tests.sh
This is regarding the issue where we have to discontinue the usage of LogDNA and use IBM Cloud Logs. While the other solution is in progress but this change is to stop sending logs to logdna. 
```
/run pipeline
```
- Use the **Squash and …
> fix: changes to avoid sending logs to logdna

- module-assets/.pre-commit-config.yaml
Remove `ibm_catalog.json` linter from pre commit hook until more stable. For example, this bug needs to be fixed: https://github.com/IBM/customized-deployable-architecture/issues/13
```
/run pipeline
```
- Use the **Squash and merge** …
> ci: remove ibm_catalog.json linter from pre commit hook until more stable

- module-assets/.pre-commit-config.yaml
- stack-assets/.pre-commit-config.yaml
Fixed the issue of deprecated stage names used by `default_stages`.
[Git issue](https://github.ibm.com/GoldenEye/issues/issues/11231)
Fixed the issue of deprecated stage names used by `default_stages`.
```
/run pipeline
```
- Use the …
> fix: deprecated stage names

- module-assets/.pre-commit-config.yaml
pre-commit are failing when they run inside the renovate docker image:
```
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/containerbase/cache/.cache/pre-commit/repo608oo3ko/golangenv-system/.install_state_v1staging'
Check the log at /tmp/containerbase/cache/.cache/pre-commit/pre-commit.log
```
Looks like same issue was reported in https://github.com/pre-commit/pre-commit/issues/3219 and the suggested fix was to change to use `system`. I tested locally and in the image and it seems to work.
If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the …
> add fix to golangci linter hook

- common-go-assets/common-permanent-resources.yaml
added elasticsearch instance CRN for backup-restore test
adds elasticsearch instance CRN for backup-restore test
```
/run pipeline
```
> feat:added elasticsearch instance CRN for backup-restore test

- module-assets/Makefile
- module-assets/docker.env
Removed `DOCKER_ENV` from Makefile - it is no longer used. It used to be used as part of an old Make command when running tests, but this command was updated a long time ago and hence is no longer used.
```
/run pipeline
```
- Use the …
> Removed `DOCKER_ENV` from Makefile - it is no longer used

- module-assets/ci/validateJsonTemplate.py
Log more details in a case `catalogValidationValues.json.template` is not valid json file.
**Examples**
```
/run pipeline
```
> fix: print error details if catalogValidationValues.json.template is not valid

- module-assets/ci/validateIbmCatalogJson.py
when pre-commit hook validates ibm_catalog.json file, it checks the `working_directory` inside `ibm_catalog.json` file.
It can happen that 2 flavors have the same `working_directory`. If pre-commit hook fails, then the following error is thrown 
If we look the error message, it seems as the same error is printed twice, which is not true (we have 2 flavors using the same value for `working_directory`. We should add more details to the error message, something like:
```
product_label: '[Add-ons Beta] RAG Pattern in Action: Application Sample'
flavor_label: 'Banking Application - Basic (Deploy on Code Engine)'
working_directory: 'solutions/bankings':
```
Run the …
> fix: display better error message for validate_ibm_catalog_json hook

- common-go-assets/common-permanent-resources.yaml
Added the current rhel-ai image name to the end of the bucket url, in order to create a complete web URL pointing to the file itself.
```
/run pipeline
```
> fix: add image name to rhelai image url

- common-go-assets/common-permanent-resources.yaml
Needed to recreate the permanent VSI snapshots, this PR will update the new IDs for those backups.
```
/run pipeline
```
> fix: updated perm snapshot values after refresh

- common-go-assets/common-permanent-resources.yaml
Removing our perm dev EnterpriseDB resources as module has been archived and service is EoL
```
/run pipeline
```
> fix: remove enterpriseDB resources

- pipeline-assets/image_vuln_scan.sh
Remove incorrect report URL from image_vuln_scan.sh. 
The new URL requires the SHA and some other details to be base64 encoded so not straugth forward to replace. Will revisit in the future perhaps, but for now removing the invalid URL that is printed in logs.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit …
> Remove incorrect report URL from image_vuln_scan.sh

- commonRenovateConfig.json
Reverts terraform-ibm-modules/common-dev-assets#1195
It seemed to cause an issue which omitted internal module updates grouping in same PRs
> Revert "Update commonRenovateConfig.json"

- .secrets.baseline
- common-go-assets/common-permanent-resources.yaml
Created a permanent secret for the Terraform Enterprise license string used for testing in the GE Dev account. This PR will add those values (the ID and CRN) in our perm resources yaml.
```
/run pipeline
```
- Use the **Squash and merge** …
> chore: add secret details for tfe license
