terraform-ibm-modules/common-dev-assets

- .github/settings.yml
Point to repo-settings repo for common configuration
> Leverage common repo settings

- module-assets/Makefile
> feat: Add support to make commands run locally

- module-assets/.pre-commit-config.yaml
> fix: ignore ekm client deb

- .github/workflows/release.yml
default versionPrefix value to 'v'
> ci: default versionPrefix value to 'v'

- .github/workflows/release.yml
- .github/workflows/terraform-module-ci.yml
Small changes to the terraform-ci and release GHA workflows to better support their usage as reusable workflow components
> ci: changes to terraform and release pipelines for reusable usage

- commonRenovateConfig.json
- add description to commonRenovateConfig.json
- cleanup some rules
> ci: add description to commonRenovateConfig.json

- module-assets/ci/run-tests.sh
https://github.ibm.com/GoldenEye/issues/issues/2212
> feat: add tekton support to run-tests.sh

- module-assets/ci/renovate-sweeper.sh
> ci: update commit message in renovate-sweeper.sh to pass commit linter

- module-assets/.terraform-docs-config.yaml
> fix: add empty line after Examples title

- module-assets/ci/terraformDocs.py
> fix: Check if examples folder exists before run add exampels script

- module-assets/Makefile
Only check for GH_TOKEN on GHE environment
> feat: only check gh_token on ghe

- module-assets/ci/terraformDocExamples.py
When running a hook inside docker container example folders are not in consistent order. Therefore we need to sort examples list.
> fix: alphabetically sort examples list

- module-assets/ci/install-deps.sh
> feat: Install terraform config inspect

- module-assets/ci/terraformDocExamples.py
Do not add examples from .tfsec folder
> fix: Example pre-commit hook adding cached examples

- module-assets/.pre-commit-config.yaml
> ci: add mixed-line-ending hook

- module-assets/Makefile
- repo_migration.sh
This script can be used to migrate the existing repositories to follow the same format as the repository template https://github.com/terraform-ibm-modules/terraform-ibm-module-template 
> feat: add migration script for existing repos

- module-assets/ci/run-catalog-onboarding-pipeline.sh
> ci: add ability to override default apikeys in catalog pipeline

- module-assets/ci/run-catalog-onboarding-pipeline.sh
- fix syntax in json command
- added error handling
- reformatted code to make more readable
> ci: fix syntax in run-catalog-onboarding-pipeline.sh and set -e

- module-assets/ci/run-catalog-onboarding-pipeline.sh
Major cleanup (with breaking changes).
Now supports parsing from ibm_catalog.json
Full working dir now needs to be passed instead of dir inside example
> Rework run-catalog-onboarding-pipeline.sh

- module-assets/ci/run-tests.sh
add ibm_catalog.json to test skip list
> ci: add ibm_catalog.json to test skip list

- module-assets/ci/run-catalog-onboarding-pipeline.sh
fix validation logic - regression introduced in https://github.com/terraform-ibm-modules/common-dev-assets/pull/126
> fix: fix validation logic

- module-assets/ci/run-catalog-onboarding-pipeline.sh
remove .git if it exists from REPO_NAME
> fix: remove .git if it exists from REPO_NAME

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Fix a word inside module template README file
> fix: Update template module README code

- module-assets/.pre-commit-config.yaml
> ci: add check-json hook

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module-tests.yaml
> fix: update .terraform-docs-config-template-module-tests.yaml

- module-assets/ci/run-catalog-onboarding-pipeline.sh
ci: sleep for 5mins between catalog pipeline
> ci: sleep for 5mins between catalog pipeline

- Brewfile
- commitlint.config.js
- module-assets/Makefile
Link to issue - https://github.ibm.com/GoldenEye/issues/issues/2680
Changes made for the local setup
* make file change
* Brew file update
* commitlint config file update
> fix: local setup updates

- module-assets/ci/module-template-automation/tests/pr_test.go
- module-assets/ci/terraformDocGoMod.py
go.mod hook should overwrite existing line
> fix: go.mod hook should overwrite existing line

- module-assets/ci/terraformDocGoMod.py
> fix: use urlparse for parsing urls

- module-assets/ci/run-catalog-onboarding-pipeline.sh
support pre and post validation scripts parsing in catalog pipeline
> ci: support pre and post validation scripts

- scripts/generate-easrsa-cert.sh
- scripts/generate-easyrsa-cert.sh
Generates the `easyrsa certs` using the script. This script is used for setting up certs for the client-to-site VPN module.
> add easyrsa script

- module-assets/ci/run-catalog-onboarding-pipeline.sh
> fix: add missing quotes

- module-assets/ci/terraformDocGoMod.py
> fix: remove .git from module_url inside gomod hook

- module-assets/ci/terraformDocGoMod.py
> fix: use lowercase comparison inside go mod hook

- module-assets/.pre-commit-config.yaml
variables inside `dynamic_values` of SLZ module shouldn't be strongly typed 
> feat: disable pre-commit-terraform hook for dynamic_values of SLZ module

- module-assets/.pre-commit-config.yaml
> fix: add a comment about  exclude hook

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module-contribution.yaml
can't find a syntax that will support a link to `<module-root>/issues`, so removing the link.
> docs: remove link to issues

- repo_migration.sh
> fix: fix soft link to .pre-commit-config.yaml

- module-assets/.pre-commit-config.yaml
- module-assets/ci/terraform-config-inspect.sh
- module-assets/ci/terraformConfigInspect.py
Generate metadata-module.json using ibm provider
> feat: use ibm provider for module-metadata generator

- module-assets/ci/terraformConfigInspect.py
> fix: do not throw error if ibm provider do not exist

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Update the readme file for the module-template to match `settings.yml` in common-dev-assets with properties that are commented out by default.
Related PR in module template: https://github.com/terraform-ibm-modules/documentation/pull/24
> docs: update readme for name and desc

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Updating changes made recently and removing need to manually set the examples in the readme.
- Update links to docs
- Remove mention of example that's not in the readme.
- Move info about examples section to pre-commit hook
> Allen fix readme

- module-assets/ci/install-deps.sh
Reverts terraform-ibm-modules/common-dev-assets#203
> Revert "ci: update to terraform 1.3.3"

- module-assets/ci/run-catalog-onboarding-pipeline.sh
Refactoring required for new catalog pipeline
> refactor: refactor ci script

- module-assets/ci/module-template-automation/common_code/.gitmodules
External and internal template module have different submodules
> fix: delete .gitmodules from module-template

- module-assets/ci/install-deps.sh
> fix: optimize installs

- module-assets/ci/terraformConfigInspect.py
Else condition is never executed. Removed extra not needed condition
> fix: remove condition inside config inspect

- module-assets/ci/terraformConfigInspect.py
fix: fix the terraform-config-inspect command
> fix: fix the terraform-config-inspect command

- module-assets/ci/install-deps.sh
> feat: add jq as a dependency

- module-assets/Makefile
> chore: updated docker run command to avoid warning on m1 mac

- module-assets/ci/cra-tf-validate-ignore-goals.json
> ci: add common cra ignore file

- common-go-assets/icd-region-prefs.yaml
> feat: add new region pref for icd modules

- module-assets/ci/terraformConfigInspect.py
> fix: always run tf upgrade inside pre-commit

- module-assets/.pre-commit-config.yaml
Need to bump checkov version to workaround bug https://github.com/bridgecrewio/checkov/issues/4011
> ci: bump checkov version 

- common-go-assets/icd-region-prefs.yaml
Finalise the aupported ICD regions for running tests. List got from https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#location
The limitation on regions comes on the keys, not ICD instances.
> update the ICD regions to be used by tests

- module-assets/ci/cra-tf-validate-ignore-goals.json
3000907 is no longer a failing goal after updating our modules to use default kube version
> 3000907 is no longer a failing goal after updating our modules to use default kube version

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
> docs: update module template docs

- module-assets/Makefile
mount all env vars starting with "MZ_" into "make run-tests" command for travis
> ci: mount all env vars starting with "MZ_" into "make run-tests" command for travis

- module-assets/.pre-commit-config.yaml
Pre-commit check 'check-json' now also checks the .releaserc file as well as .json files.
> feat: check json also checks .releaserc

- module-assets/ci/run-tests.sh
Current variables not working in tekton
> Fix the REPO_NAME and PR_NUM variables in run-tests.sh for Tekton use case

- module-assets/ci/run-tests.sh
- combined the 2 tags into one tag to make it easier to filer in logdna
- redirect both stdout and stderr to log file
> ci: update MZ_TAGS in run_tests.sh

- module-assets/ci/submoduleVersionCheck.sh
There seems to be an issue with this change so need to revert until we fix
> Revert "fix: git-submodule-version-check hook check version with local primary branch"

- module-assets/ci/submoduleVersionCheck.sh
> fix: submodule hook to get the right version of submodule

- module-assets/ci/run-cra.sh
Adding IBM CRA Scan for use in pipelines
---
> feat: add cra scan for gha

- module-assets/ci/run-cra.sh
Forgot to re-enable terraform init before merging
---
> Enable init

- module-assets/ci/run-cra.sh
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.
---
> Fail Script If any command fails

- common-go-assets/cloudinfo-region-vpc-gen2-prefs.yaml
AT is back working again in eu-gb
---
> ci: enable eu-gb region for tests again

- module-assets/ci/run-cra.sh
Need the pipeline to continue if the CRA fails so we can check if the failures are to be ignored.
---
> Do not fail pipeline if CRA scan Fails

- module-assets/ci/terraformDocGoMod.py
> feat: go_mod pre-commit hook supports forks

- module-assets/ci/install-deps.sh
> ci: bump to tf 1.3.7

- .github/workflows/ci.yml
Workaround for https://github.com/actions/runner/issues/2033
---
> ci: unblock pipeline

- module-assets/.pre-commit-config.yaml
- renovate.json
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.
---
> fix: pin isort to fix 

- module-assets/Makefile
Workaround for our travis pipeline (issue https://github.com/actions/runner/issues/2033)
---
> ci: add workaround to make commands for travis

- module-assets/Makefile
ci: add missing $ from make commands
---
> ci: add missing $ from make commands

- module-assets/ci/renovate-sweeper.sh
remove verbose logging from renovate-sweeper.sh
---
> ci: remove verbose logging from renovate-sweeper.sh

- module-assets/ci/renovate-sweeper.sh
[Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.](ci: remove debug print from renovate-sweeper.sh)
---
> ci: remove debug print from renovate-sweeper.sh

- .github/settings.yml
> docs: update repo description

- common-go-assets/common-permanent-resources.yaml
added Service dnlb IAM serviceID
N/A
---
> feat: added Service dnlb IAM serviceID

- common-go-assets/common-permanent-resources.yaml
add activityTrackerFrankfurtResourceKeyName to common yaml
---
> ci: add activityTrackerFrankfurtResourceKeyName to common yaml

- common-go-assets/common-permanent-resources.yaml
Add cloudant dedicated host crn to the common-permanent-resources.yaml
---
> ci: add cloudant dedicated host to common-permanent-resources.yaml

- common-go-assets/common-permanent-resources.yaml
modified : common-go-assets/common-permanent-resources.yaml
added activityTrackerFrankfurtRegion to common yaml
needed for issue  https://github.ibm.com/GoldenEye/at-views-alerts-module/pull/345
---
> ci: add activityTrackerFrankfurtRegion to common yaml

- common-go-assets/common-permanent-resources.yaml
Adding new permanent resources
---
> feat: add access tags to perm resources

- common-go-assets/common-permanent-resources.yaml
A potential bug in CBR means the key needs to be unique so removing some of the tags until the issue is resolved
---
> fix: Change tags due to CBR limitations

- module-assets/ci/run-catalog-onboarding-pipeline.sh
Making it clear that flavor label (not name) has to be used here
---
> updates around flavor label in run-catalog-onboarding-pipeline.sh

- module-assets/ci/run-tests.sh
Added .preset.json to files that should not trigger tests
---
The commit message determines whether a new version of the module is needed, and if so, which …
> Do not trigger tests for .preset.json

- module-assets/ci/install-deps.sh
> feat: use tfswitch to determine tf version to install

- common-go-assets/common-permanent-resources.yaml
> Update common-permanent-resources.yaml hpcs Root Key crns

- module-assets/ci/module-template-automation/tests/other_test.go
- module-assets/ci/module-template-automation/tests/pr_test.go
Update tests in module template to use setupOptions 
https://github.ibm.com/GoldenEye/issues/issues/4082
---
> test: update tests in the template modules

- .gitignore
- common-go-assets/common-permanent-resources.yaml
Added static resources to perform tests for crossaccount transit gateway configuration
Added static resources values
---
> feat: static resources for crossaccounts tg tests

- common-go-assets/common-permanent-resources.yaml
Added CRN of postgresql instance
---
> refactor: Update common-permanent-resources.yaml

- module-assets/ci/run-cra.sh
Output the CRA plugin details so we know exact version that is being run in the pipeline. 
Output looks like this:
```
% ibmcloud plugin show cra   
Plugin Name                              cra
Plugin Version                           1.2.0
Plugin SDK Version                       0.6.8
Minimal IBM Cloud CLI version required   0.0.1
Private endpoints supported              false
Commands:
cra                           Discover code vulnerabilities
cra bom-generate,bom          Generate bill of materials listing all OS and app package dependencies
cra deployment-analyze,depl   Detect vulnerabilities in Kubernetes files
cra terraform-validate,tf     Validates Terraform configuration against goals defined in IBM Security and Compliance Center.
cra vulnerability-scan,cve    Scan a Bill of …
```
> feat: output the CRA plugin details

- module-assets/ci/run-cra.sh
Reverts terraform-ibm-modules/common-dev-assets#568
Will include in pipeline code instead (see https://github.com/terraform-ibm-modules/common-pipeline-assets/pull/428)
> Revert "feat: output the CRA plugin details"

- module-assets/ci/run-catalog-onboarding-pipeline.sh
- Always require `ibm_catalog.json` to exist if you want to import to catalog
- `flavor_label_array` is now `directory_array` since it is possible to have multiple flavors with the same label name - the working directory will however always be unique, as well as the install_type
---
The commit message determines whether a new version of the module is needed, and if …
> ci: updates to run-catalog-onboarding-pipeline.sh

- module-assets/ci/run-catalog-onboarding-pipeline.sh
I changed the sleep to 10secs, but we faced 409s. Changing back sleep to 5mins to avoid 409s
---
> ci: sleep for 5mins to avoid 409s

- module-assets/Makefile
Full details of this change can be found in https://github.ibm.com/GoldenEye/issues/issues/4643
Fix has been tested on Docker Desktop and Rancher Desktop with the dockerd (moby) container engine
---
> ci: fix the docker-run command for rancher

- .secrets.baseline
- module-assets/ci/run-cra-scc-v2.sh
> Output Policy ID for debugging

- module-assets/ci/install-deps.sh
Follow on to https://github.com/terraform-ibm-modules/common-dev-assets/pull/604
---
> ci: bump detect secrets version in install-deps.sh

- module-assets/ci/run-catalog-onboarding-pipeline.sh
Update run-catalog-onboarding-pipeline.sh to hard fail if working_dir does not exist. Long term, I'll see about removing this dependency 
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR …
> Update run-catalog-onboarding-pipeline.sh to hard fail if working_dir does not exist

- common-go-assets/icd-region-prefs.yaml
update icd region list, it was missing us-east
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines …
> ci: update icd region list

- commonRenovateConfig.json
Need to run `pre-commit install` before running `pre-commit run --all-files`
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
--- …
> Update commonRenovateConfig.json - run "pre-commit install" before running "pre-commit run --all-files"

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
Follows what we implemented in https://github.ibm.com/GoldenEye/namespace-module/#compliance-and-security
Run the CI …
> add negative statement about controls to readme

- scripts/update-multiple-repos/README.md
- scripts/update-multiple-repos/updateRepos.sh
> feat: add script to push updates to all repos into source control

- common-go-assets/common-permanent-resources.yaml
Need to update the SM instance GUID due to an issue with out old one
Run the CI pipeline when the PR is ready for review …
> Update SM instance guid in common-permanent-resources.yaml

- common-go-assets/cloudinfo-region-power-prefs.yaml
switch lon regions
If the CI pipeline …
> fix: Update cloudinfo-region-power-prefs.yaml

- .github/workflows/ci.yml
renovate no longer needs this as it is using its own post update commands
Run the CI pipeline when the PR is ready for …
> remove renovate-sweeper from ci.yml

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
remove "Build status" badge from module template
Run the CI pipeline when the PR is ready for review and you expect …
> ci: remove "Build status" badge from module template

- module-assets/ci/run-cra-scc-v2.sh
fix bug in CRA script which can cause CRA to pass when it never actually ran
Run the CI pipeline when the PR is ready …
> fix: fix bug in CRA script

- common-go-assets/common-permanent-resources.yaml
SLZ needs the hpcs instance name and resource group so adding these to the common file
Run the CI pipeline when the PR …
> feat: add hpcs details for slz

- common-go-assets/common-permanent-resources.yaml
Provided the provisioned Enterprise Database CRN information.
Run the CI pipeline when the PR is ready for review and …
> feat: updated enterprise db crn

- module-assets/.pre-commit-config.yaml
update tf validate to validate `examples`, `patterns` and `solutions` folders (if they exist)
Run the CI pipeline when …
> ci: update tf validate to validate other folders too

- common-go-assets/cloudinfo-region-power-prefs.yaml
Update preference for powervs DC
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …
> ci: update priority powervs regions

- module-assets/ci/module-template-automation/examples/default/main.tf
- scripts/update-source/run-update-src.py
As part of https://github.ibm.com/GoldenEye/issues/issues/4214, fixed the following bugs 
- id and version variables are not defined initially
- fix regex pattern to update modules section in README.md
- exclude directories (common-dev-assets and ci) when updating references from the module
Your notes help the merger write the commit message for the PR that is …
> fix: update src script

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
final few bits of cleanup
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …
> docs: mod template cleanup

- module-assets/ci/module-template-automation/examples/basic/version.tf
No need to add range when we lock into exact version
Run the CI pipeline when the PR is ready for review and you expect …
> ci: fix version in basic example of mod template

- module-assets/ci/run-tests.sh
Don't run infra tests if only updating cra-config.yaml file
Run the CI pipeline when the PR is ready for review and you …
> ci: Don't run infra tests if only updating cra-config.yaml file

- module-assets/ci/run-cra-scc-v2.sh
Migrate to instances api in CRA script
- account ID replaced with Instance Id
- SCC region now needs to be passed
Run …
> fix: migrate to instances api in CRA script

- commonRenovateConfig.json
Grouping CI related renovate PRs into a single PR to reduce the number of renovate PRs we are creating
Run the CI …
> ci: grouping CI related renovate PRs into a single PR to reduce the number of renovate PRs we are creating

- module-assets/.pre-commit-config.yaml
- renovate.json
Now that we have updated the python version to 3.10 in our CI image, we can now upgrade to the latest iSort version
Run …
> ci: upgrade to latest iSort version

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
> fix: add toc hook to template module

- module-assets/ci/terraformDocsUtils.py
> fix: add get_module_url to docs utils

- module-assets/.pre-commit-config.yaml
> fix: remove default terraform_docs pre-commit hook

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
- module-assets/ci/module-template-automation/overview-external.md
- module-assets/ci/module-template-automation/overview-internal.md
- module-assets/ci/module-template-automation/required_iam_access_policies.md
- module-assets/ci/module-template-automation/toc.md
> docs: add overview to module template

- module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml
> fix: update headings for template module

- module-assets/ci/terraformDocs.py
run terraform docs hook only if metadata exists
Run the CI pipeline when the PR is ready for review and you expect tests …
> fix: run terraform docs hook only if metadata exists

- scripts/update-multiple-repos/updateRepos.sh
```
Important: github.ibm.com no longer uses a wildcard certificate. If you have been using "api.github.ibm.com" anywhere in your codebase, change it IMMEDIATELY to "github.ibm.com/api/v3/" to avoid code breakage.
Please reference the GitHub Enterprise Server@3.3 documentation for api request examples
```
Your notes help the merger write the commit message for the PR …
> Update github api call

- commonRenovateConfig.json
Some modules have terraform code in `tests/resources` - for these we don't need to create a new release, so the new config in this PR will ensure this is the case by using `chore` as its commit message prefix …
> ci: update renovate config

- module-assets/.pre-commit-config.yaml
- module-assets/.terraform-docs-config.yaml
- module-assets/ci/terraformDocs.py
- module-assets/ci/terraformDocsUtils.py
Fix for https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/270
Run the CI pipeline when the PR is ready …
> fix: fix so that custom terradocs hook runs against all markdown files with the metadata

- module-assets/.pre-commit-config.yaml
- module-assets/.terraform-docs-config.yaml
- module-assets/ci/terraformDocs.py
- module-assets/ci/terraformDocsUtils.py
Reverts terraform-ibm-modules/common-dev-assets#703
> Revert "fix: fix so that custom terradocs hook runs against all markdown files with the metadata"

- module-assets/.pre-commit-config.yaml
- module-assets/ci/terraformDocs.py
- module-assets/ci/terraformDocsUtils.py
Fix for https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/270
Run the CI pipeline when the PR is ready …
> fix: update custom terradocs hook to run on every readme with metadata tags

- common-go-assets/common-permanent-resources.yaml
avoid nuking by adding prefix
https://github.ibm.com/GoldenEye/issues/issues/5348
```
/run pipeline
```
> fix: add geretain prefix to avoid nuking keys

- module-assets/.pre-commit-config.yaml
- module-assets/Makefile
> remove commit format requirement

- common-go-assets/common-permanent-resources.yaml
added cis details for public cert secrets test
```
/run pipeline
```
> feat: added cis details for public cert secrets test

- module-assets/ci/run-catalog-onboarding-pipeline.sh
Add support to destroy resources and/or workspace in run-catalog-onboarding-pipeline.sh
```
/run pipeline
```
> Add support to destroy resources and/or workspace in run-catalog-onboarding-pipeline.sh

- module-assets/ci/install-deps.sh
BSL license only came in 1.6, so ok to lock into latest 1.5.x version
```
/run pipeline
```
> Lock into TF 1.5.7

- module-assets/ci/terraformConfigInspect.py
If hook fails, do not change module-metadata.json file
if hook fails then displays an error
```
Generate terraform module metadata.......................................Failed
- hook id: terraform-config-inspect
- duration: 10.12s
- exit code: 2
b'unknown flag: --jsson\nUsage of terraform-config-inspect:\n      --filter-variables   produce JSON-formatted output for variables\n      --json               produce JSON-formatted output\n      --metadata string    Provider metadata json file path\n'
```
```
/run pipeline
```
- Use a …
> fix: do not change module-metadata.json if hook fails

- module-assets/.pre-commit-config.yaml
> Add comment in .pre-commit-config.yaml

- common-go-assets/common-permanent-resources.yaml
Added permanent resources for ESO module tests
Added permanent resources for ESO module tests
```
/run pipeline
```
> eso module permanent resources

- common-go-assets/cloudinfo-region-power-prefs.yaml
changing regions order due to atracker resources
```
/run pipeline
```
> fix: regions

- module-assets/.pre-commit-config.yaml
> update ignored directories

- common-go-assets/cloudinfo-region-secmgr-prefs.yaml
- common-go-assets/cloudinfo-region-vpc-gen2-prefs.yaml
Support for Madrid DC. Both SM and VPC are available in the MZR and can be used for testing
Note that Madrid is being added.
```
/run pipeline
```
> Support Madrid DC

- common-go-assets/common-permanent-resources.yaml
Updated static parameters for tests
```
/run pipeline
```
> updated static parameters

- common-go-assets/common-permanent-resources.yaml
Added ge ops and KP details
```
/run pipeline
```
> added ge ops and KP details

- module-assets/.pre-commit-config.yaml
- module-assets/ci/terraformDocs.py
hook didn't run on `git commit`
```
/run pipeline
```
> fix: update terraform_docs hook to run on git commit

- module-assets/.pre-commit-config.yaml
> fix: do not pass files for tf docs pre-commit hook

- module-assets/.pre-commit-config.yaml
See https://github.com/bridgecrewio/checkov/issues/5855
```
/run pipeline
```
> Skip CKV2_IBM_6

- module-assets/.pre-commit-config.yaml
> Remove any refs to "module-metadata.json" in .pre-commit-config.yaml

- module-assets/ci/run-tests.sh
> ci: remove trace logs from run-tests.sh

- module-assets/ci/run-tests.sh
> Update debug prints in run-tests.sh

- module-assets/ci/run-tests.sh
Updated match check to check array content rather than length.
```
/run pipeline
```
> Empty commit fix

- module-assets/ci/run-tests.sh
> remove debug prints and update logic to skip tests if PR contains no files in it

- module-assets/ci/terraformDocs.py
> feat: add support for tf_docs pre-commit hook to run inside multiple subfolders

- module-assets/ci/terraformDocs.py
> fix: run tf_docs hook against each README separately

- common-go-assets/common-permanent-resources.yaml
Added HPCS endpoints URLs
```
/run pipeline
```
> added HPCS endpoints URLs

- common-go-assets/common-permanent-resources.yaml
Added permanent MySQL resources to the `common-permanent-resources.yaml` file.
```
/run pipeline
```
> feat: added mysql to perm resource yaml

- module-assets/ci/golangci-lint.sh
Update golang linter script as it had a bug.
```
/run pipeline
```
> fix: golang linter

- common-go-assets/common-permanent-resources.yaml
Add test domains to permanent resources
```
/run pipeline
```
> fix: Add domains as permanent resources

- module-assets/ci/run-tests.sh
Debugging issue with forks and running tests.
```
/run pipeline
```
> fix: fork bug

- module-assets/ci/run-tests.sh
> fix: add logging lines to debug issue

- module-assets/ci/install-deps.sh
> fix: use the right trivity arch for ubuntu

- module-assets/.pre-commit-config.yaml
> update terraform_trivy to ignore terraform cache directory

- module-assets/.pre-commit-config.yaml
- module-assets/ci/trivy.sh
NOTE: we found solution to use arguments with `terraform_trivy`. therefore we will go with that approach
bellow is deprecated
terraform_trivy pre-commit hook has issues by passing `--skip-dirs` argument. In addition we could use customized pre-commit hook
Current implementation:
- scan against all files, skipping all `.terraform` folders
- hook fails if `CRITICAL,HIGH,LOW` issues are found
hook fails if issues are found
hook passes if no issues
```
/run pipeline
```
- Use a conventional commit message to set the release level. …
> fix: use trivy as a customized pre-commit hook

- common-go-assets/common-permanent-resources.yaml
Added IBM MQ Queue Manager license and usage.
```
/run pipeline
```
> added mq queue manager license and usage

- module-assets/ci/run-tests.sh
> Update run-tests.sh to ignore .trivyignore

- module-assets/ci/run-tests.sh
Remove excess logs in tests.
```
/run pipeline
```
> fix: remove excess logs

- module-assets/ci/golangci-lint.sh
> fix: enable debug mode golangci-lint timeout

- module-assets/ci/golangci-lint.sh
> fix: increase golangci pre-commit hook timeout

- common-go-assets/common-permanent-resources.yaml
> ci: add code engine public certificate id to common pernament resources

- common-go-assets/common-permanent-resources.yaml
> ci: add code engine public cert common name into pernament resources

- common-go-assets/common-permanent-resources.yaml
Added CRNs for mongo and rabbitmq.
Issues: https://github.ibm.com/GoldenEye/issues/issues/7964 and https://github.ibm.com/GoldenEye/issues/issues/7963.
```
/run pipeline
```
> Added CRNs for mongo and rabbitmq

- module-assets/ci/run-tests.sh
> remove verbose logging from run-tests.sh

- commonRenovateConfig.json
- module-assets/.pre-commit-config.yaml
Updates to match the new naming convention rolled out in https://github.com/terraform-ibm-modules/terraform-ibm-module-template/pull/763
```
/run pipeline
```
> update some CI things for deployable modules

- module-assets/ci/install-deps.sh
> Fix bug in install-deps.sh

- common-go-assets/common-permanent-resources.yaml
> add mas secrets

- stack-assets/stack-updater/README.md
- stack-assets/stack-updater/requirements.txt
- stack-assets/stack-updater/update_stack_definition.py
Script to update stack definition 
```
/run pipeline
```
> stack updater

- module-assets/.pre-commit-config.yaml
Fix for this:
```
/run pipeline
```
> Update .pre-commit-config.yaml to allow .tar.gz to be committed

- stack-assets/.pre-commit-config.yaml
> Update stacks common .pre-commit-config.yaml

- module-assets/ci/validateJsonTemplate.py
> ci: do not validate ibmcloud_api_key as part of stack's json template

- module-assets/ci/validateJsonTemplate.py
> ci: fix validate json template lint hook

- common-go-assets/common-permanent-resources.yaml
Add reservation_id_secret_id
```
/run pipeline
```
> Add reservation_id_secret_id

- examples/mock_tf_code/version.tf
- module-assets/ci/install-deps.sh
> Update to terraform 1.6.6

- stack-assets/stack-updater/update_stack_definition.py
> add newline to end of updated def file

- stack-assets/stack-updater/update_stack_definition.py
> Update stack script

- module-assets/Makefile
> Update Makefile - remove terragrunt

- common-go-assets/common-permanent-resources.yaml
> feat: add atracker trusted profile

- module-assets/ci/validateJsonTemplate.py
The linter fails for this:
`{"ibmcloud_api_key": $VALIDATION_APIKEY, "resource_group": $RG_NAME, "resource_tags": $TAGS, "prefix": $PREFIX}`
But passes for this:
```
{
"ibmcloud_api_key": $VALIDATION_APIKEY,
"resource_group": $RG_NAME,
"resource_tags": $TAGS,
"prefix": $PREFIX
}
```
Both are valid JSON. The linter should not mandate that the output is pretty
```
/run pipeline
``` …
> ci: do not fail catalogValidationValues.json.template linter hook if format is not pretty

- module-assets/.pre-commit-config.yaml
- module-assets/ci/terraformDocOverview.py
fixing:
- No such file or directory: 'overview.md'
- cannot access local variable 'data' where it is not associated with a value
```
/run pipeline
```
> fix: do not pass all files to overview pre-commit hook

- common-go-assets/common-permanent-resources.yaml
Adds new Snapshot Consistency Group permanent test resources to yaml.
```
/run pipeline
```
> test: add snapshot group perm resources

- module-assets/.pre-commit-config.yaml
> fix: skip observability helm-chart checks

- stack-assets/stack-updater/requirements.txt
- stack-assets/stack-updater/update_stack_definition.py
> update to sort on version

- common-go-assets/common-permanent-resources.yaml
> feat: add etcd permanent resources

- module-assets/ci/run-tests.sh
- Updated script to check `if ${pr_test_file}` exists as a regular file using `test -f`
- Refer [Issue](https://github.ibm.com/GoldenEye/issues/issues/10037)
```
/run pipeline
```
> fix: corrected test argument name

- common-go-assets/common-permanent-resources.yaml
Add the GUID for a shared MQ on Cloud service instance with plan of reserved-capacity.
This service instance should be used by all tests that require MQ on Cloud service instances with a plan of reserved-deployment.
```
/run pipeline
``` …
> feat: Add MQ capacity plan guid

- stack-assets/stack-updater/update_stack_definition.py
> update logger and debug logs

- module-assets/ci/install-deps.sh
- renovate.json
Now that Schematics supports terraform 1.9, we can update our CI script to install it. 
If any of our modules have issues on 1.9, the tests won't all of a sudden break, the renovate PR which updates the GIT submodule would fail the tests and we would catch it then.
I added a renovate rule which prevent the major and minor tf version from being updated.
I removed tofu from the dependency list - no plans to use it.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> Update to terraform 1.9.6

- module-assets/ci/install-deps.sh
> Lock into tf 1.9.2 to match schematics support

- stack-assets/stack-updater/update_stack_definition.py
Optionally output a changelog to a csv file when updating a stack.
```
/run pipeline
```
> feat: track changelog with stack update

- common-go-assets/prometheus-helm-values.yaml
This PR adds helm yaml values for Prometheus agent which will be used by Prometheus agent DA in tests.
https://github.ibm.com/GoldenEye/issues/issues/10866
Adds helm yaml values for Prometheus agent
```
/run pipeline
```
- Use the …
> Add prometheus-helm-values.yaml

- common-go-assets/common-permanent-resources.yaml
added secretID for public github token for dev account
```
/run pipeline
```
> feat: added secretID for public github token for dev account

- common-go-assets/common-permanent-resources.yaml
HPCS API endpoints have changed
HPCS API endpoints have changed to use a new format.
```
/run pipeline
```
> feat: update hpcs endpoints

- pipeline-assets/publish.sh
https://github.ibm.com/GoldenEye/issues/issues/11301
```
/run pipeline
```
> Update how we check the pipeline status

- common-go-assets/common-permanent-resources.yaml
Added permanent  Event Streams crn
```
/run pipeline
```
> added permanent  Event Streams crn

- common-go-assets/common-permanent-resources.yaml
Added secretIDs for the subscriptionIDs to use to deploy DB2, MQ and EASe4J
Secrets stored on permanent SM
```
/run pipeline
```
> Added secretIDs for the subscriptionIDs for AppMod deployment of DB2, MQ and EASe4J

- common-go-assets/common-permanent-resources.yaml
added private only secrets manager info to permanent resources yaml
```
/run pipeline
```
> feat: added private only sm info to permanent resources yaml

- common-go-assets/common-permanent-resources.yaml
Required for internal AIRT module tests
```
/run pipeline
```
> Add `atracker_trusted_profile_iam_id` to common-permanent-resources.yaml

- module-assets/.pre-commit-config.yaml
- renovate.json
- stack-assets/.pre-commit-config.yaml
- bump to the latest version of checkov since the https://github.com/bridgecrewio/checkov/issues/5945 is now longer occurring
- remove renaoate rule which was preventing the version from being updated (o=also removed a rule about tf version which is not used since we always lock to exact version schematics is on)
- Removed `--skip-check=CKV2_IBM_6` since this issue was fixed by checkov
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> Update to the latest checkov version

- common-go-assets/common-permanent-resources.yaml
> Add `account_level_tenant_crn` to common-permanent-resources.yaml

- common-go-assets/common-permanent-resources.yaml
Adds permanent redis instance CRN for backup test.
```
/run pipeline
```
> add: permanent backup redis instance

- common-go-assets/common-permanent-resources.yaml
Updated secret ID with ID of restored secret been destroyed
```
/run pipeline
```
> fix: created new secret and updated the ID

- common-go-assets/common-permanent-resources.yaml
Added permanent cloud logs instance in permanent resources
```
/run pipeline
```
> Added permanent cloud logs instance in permanent resources

- common-go-assets/common-permanent-resources.yaml
Added some references in the permanant resources yaml file for new rhelai project resources.
```
/run pipeline
```
> feat: add perm resources for rhelai storage

- module-assets/.pre-commit-config.yaml
- module-assets/ci/terraformDocOverview.py
The problem is that the example had README.MD file. Extension of a file is upper case and current implementationhas issues to find a file on a linux (while works on MAC).
I used different approach to search for README files where case is insensitive.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes …
> fix: scan examples and modules that have README file in anycase

- module-assets/.pre-commit-config.yaml
> fix: skip rule which checks for the type of lb

- common-go-assets/common-permanent-resources.yaml
instance no longer eixsts
```
/run pipeline
```
> remove HPCS us-east details common-permanent-resources.yaml

- common-go-assets/common-permanent-resources.yaml
Removed db2 instance to use for e4j module tests
```
/run pipeline
```
> Removed db2 instance to use for e4j module tests

- module-assets/.pre-commit-config.yaml
This PR was just merged: https://github.com/bridgecrewio/checkov/issues/7009
When it is included in a new version of checkov, update the version and remove the workaround in https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets/.pre-commit-config.yaml to ignore CKV2_IBM_1
```
/run pipeline
```
- Include information that users need to know about the …
> fix: remove checkov ignore of `CKV2_IBM_1` in .pre-commit-config.yaml

- module-assets/ci/install-deps.sh
> bump to terraform 1.10.5

- module-assets/.pre-commit-config.yaml
Added pre-commit check to check the schema for the ibm_catalog.json and ensure it is valid.
```
/run pipeline
```
> feat: add ibm_catalog.json precommit check

- examples/Dockerfile
- examples/mock_tf_code/main.tf
- examples/mock_tf_code/variables.tf
- module-assets/.pre-commit-config.yaml
- module-assets/ci/install-deps.sh
> chore: add an example using dynamic block to catch more trivy errors

- module-assets/.pre-commit-config.yaml
- module-assets/ci/validateIbmCatalogJson.py
Skip elements from a hook scanning if a key has `virtual: true`
```
/run pipeline
```
> fix: add option to skip elements from validate_ibm_catalog_json hook

- commonRenovateConfig.json
> Add provider updates into same renovate PRs as module updates

- common-go-assets/common-permanent-resources.yaml
Refresh the code engine public certificate secret ID
```
/run pipeline
```
> fix: update code engine public certificate secret id

- module-assets/ci/run-tests.sh
> Trigger tests if ibm_catalog.json is updated

- commonRenovateConfig.json
> recreate the PR if something has actually changed, not on every cycle

- .secrets.baseline
- pipeline-assets/contanerize.sh
- pipeline-assets/image_vuln_scan.sh
> add support for prisma scan

- pipeline-assets/contanerize.sh
Docker push failed with intermittent issue, but it didn't hard fail and tried to do image scan which failed:
```
ibmcloud cr region-set global
The region is set to 'global', the registry is '[icr.io](http://icr.io/)'.
OK
ibmcloud cr login
Logging 'docker' in to '[icr.io](http://icr.io/)'...
FAILED
Failed to 'docker login' to '[icr.io](http://icr.io/)' with error: Error response from daemon: Get "https://icr.io/v2/": Get "https://icr.io/oauth/token?account=iamrefresh&client_id=docker&offline_token=true&service=registry": EOF
.
make: *** [Makefile:47: docker-login] Error 1
./common-dev-assets/pipeline-assets/image_vuln_scan.sh: line 99: [: : integer expression expected
./common-dev-assets/pipeline-assets/image_vuln_scan.sh: line 107: [: : integer expression expected
```
This fix will now …
> Update contanerize.sh - only proceed to scan if docker push is succesful

- module-assets/ci/install-deps.sh
https://github.ibm.com/GoldenEye/issues/issues/15043
Added a check for Go in the dependency installation script
This PR is for adding a check for Go in the dependency installation script
```
/run pipeline
```
- Use the **Squash and …
> fix: check for go

- module-assets/ci/validateIbmCatalogJson.py
examples of the error
```bash
Validate ibm_catalog.json file...........................................Failed
- hook id: validate_ibm_catalog_json
- duration: 0.18s
- exit code: 1
product_label: 'Cloud automation for Databases for Elasticsearch'
flavor_label: 'Standard'
working_directory: 'solutions/standard':
- key 'terraform_version' is missing
```
```bash
Validate ibm_catalog.json file...........................................Failed
- hook id: validate_ibm_catalog_json
- duration: 0.08s
- exit code: 1
product_label: 'Cloud automation for Databases for Elasticsearch'
flavor_label: 'Standard'
working_directory: 'solutions/standard':
- key 'terraform_version': '1.10' not the right format. Should be locked to a version and have MAJOR.MINOR.PATCH format.
```
If the CI pipeline doesn't run …
> feat: validate if ibm_catalog_json has terraform_version key

- shared-pipeline/report.sh
- shared-pipeline/setup.sh
> feat: add common pipeline files:

- shared-pipeline/setup.sh
> fix: move around github auth

- module-assets/.pre-commit-config.yaml
- Added missed ignore file in command
- Romoved backtics in suggesstions
Removed backticks, looks bit cleaner
```
/run pipeline
```
> removed backticks from typos suggesstions

- module-assets/ci/validateIbmCatalogJson.py
Updates `ibm_catalog.json` formatting if needed. 
The pre-commit hook fails on the first run due to formatting issues but corrects the JSON. On the second run, it passes successfully.
```
/run pipeline
```
- Use the **Squash and merge** …
> fix: update JSON validate pre-commit hook to check JSON formatting

- stack-assets/.pre-commit-config.yaml
> add workaround for detect secrets in stacks hook

- module-assets/.pre-commit-config.yaml
- stack-assets/.pre-commit-config.yaml
> Remove detect secrets hook workaround
